### PR TITLE
3.1 FoxxHandler.php (fulfilling #191)

### PR DESCRIPTION
**Pull request by tomterl**
This pull-request is the 3.1 foxx-api implementation to upload/install and uninstall foxx-applications via php-code as promised in #191. 

If the code or tests need adjustments, please comment.

### CODE REVIEW

**Comment by tomterl** [comment]
Hmm - the test failes because `static::expectedException()` is undefined for php-5.5

**Comment by tomterl** [comment]
I have a copy of the CLA and see to it, that I send it to you ASAP, after clarifying the details with my employer.

**Comment by frankmayer** [comment]
Hi @tomterl, thanks for your contribution. Code looks good and tests pass, so, as soon as the CLA is received on ArangoDB's side, we're good to merge.

**Comment by jsteemann** [comment]
Thanks. Looking forward to merging this.

**Comment by tomterl** [comment]
There was a 'red-tape incident' -- the cla got lost in the process of getting it approved and signed ;-) -- I just forwarded the pdf and hope that it won't take too long now;

**Comment by tomterl** [comment]
I just heard the CLA should have reached you already -- Franke & Bornberg ist the corporate entity in question. Let me know, if you need anything else from me.

**Comment by jsteemann** [comment]
Yes, we got such CLA. I wasn't aware the company was related to this PR. Will merge then.

**Comment by jsteemann** [comment]
Thanks a lot for the patch. I merged the PR into 3.1, and manually applied the patch in the devel branch.

**Comment by frankmayer** [comment]
@jsteemann there was a broken test-process with HHVM in Travis, which I missed in my previous commit. It was thus showing `build error`. I restarted it and this is now fixed, too.

**Comment by jsteemann** [comment]
@frankmayer: thanks!
@tomterl: thanks again for the patch!

**Pull request merged**
