### PR TITLE
Fix document ids

### PR DESCRIPTION
**Pull request by frankmayer**
A stab at fixing the document id problem, that was reported in issue #210.

### CODE REVIEW

**Comment by frankmayer** [comment]
Could it be that the nightly ArangoDB tarball that is downloaded on travis is not up to date? The failed test has something to do with a recent change to devel and it doesn't fail locally on an 3.1.13 installation.

**Comment by jsteemann** [comment]
Thanks!! :thumbsup:

**Comment by frankmayer** [comment]
@jsteemann My pleasure :smile: 
BTW, could you pls take a look at why the one test is constantly failing in devel? It seems to have something to do with the nightly tarball, as that test does not fail on my fresh local 3.1.13 installation.

**Comment by jsteemann** [comment]
It's a problem with the devel version fetched by TravisCI being outdated.
There should be a fresh nightly build image for TravisCI each day/night, but the build job for producing this image is currently broken. 
A colleague of mine is working on replacing this job with an entirely new build job, which will not only build the daily/nightly images for TravisCI but for all supported platforms. I have been pushing for this for quite a while and hope the new build job will be ready this week. Then the TravisCI tests will run against current devel and the PHP driver's test should succeed again.

**Comment by frankmayer** [comment]
OK, I suspected so. 
Great. Hoping for a quick resolution of that issue, then. 
Thanks!

**Comment by jsteemann** [comment]
Me too!

**Pull request merged**
