### PR TITLE
Simplify composer installation instructions

### PR DESCRIPTION
**Pull request by guiwoda**
You shouldn't document how to use composer in this library. 
Assume composer knowledge, and maybe add a link to its docs if you feel instructions aren't clear enough.

Check [any](https://github.com/thephpleague/flysystem) [other](https://github.com/laravel/socialite) [php](https://github.com/zendframework/zend-diactoros/blob/master/doc/book/install.md) [library](https://symfony.com/doc/current/components/using_components.html) out there for conventions on composer docs.

Previous docs were too verbose and people with knowledge of composer would have to dig deep to find the package name (or end up looking for it in your `composer.json` instead of the README file.)

### CODE REVIEW

**Comment by jsteemann** [comment]
Thanks for providing this patch!

I am happy to accept the patch, but for legal reasons we need you to fill out and sign our Contributor License Agreement (CLA). You can scan and email the [CLA PDF file](https://www.arangodb.com/documents/cla.pdf) to cla@arangodb.com or send it via fax to +49-221-2722999-88. 
Sorry for the inconvenience, but once the agreement is there the PR can be merged.

**Comment by frankmayer** [comment]
Hi @guiwoda. Thanks for this PR. 
Can we expect a signed CLA from you in order to be able to merge this PR or should I go ahead and make the necessary changes in a separate commit?

**Comment by guiwoda** [comment]
You can commit separately, I completely forgot about this and I'm not using
the library now, so I don't think I'll be sending PRs this way anyway.

**Comment by frankmayer** [comment]
This was implemented and further changed in a separate commit.
Thank you for your effort, @guiwoda

**Pull request closed without merging**
