### PR TITLE
Add optional body param to delete request

### LINKED ISSUE #233: Missing optional body param for delete request to remove multiple documents
The method [\ArangoDBClient\Connection::delete](https://github.com/arangodb/arangodb-php/blob/devel/lib/ArangoDBClient/Connection.php#L295) needs an optional body param to [remove multiple documents](https://docs.arangodb.com/3.3/HTTP/Document/WorkingWithDocuments.html#removes-multiple-documents).

To avoid a BC break, I recommend to add it as a third optional argument. What do you think?

### PR DESCRIPTION
**Pull request by sandrokeil**
Close #233

### CODE REVIEW

**Comment by jsteemann** [comment]
I am happy to accept the patch, but for legal reasons you will need to fill out and sign our [Contributor License Agreement](https://www.arangodb.com/documents/cla.pdf). You can scan and email the pdf file to cla@arangodb.com or send it via fax to +49-221-2722999-88. Sorry for the inconvenience, but once the agreement is there this PR and any following can be merged easily.

**Comment by sandrokeil** [comment]
@jsteemann I've signed the CLA. It looks like the Travis config is out of date.

```
pwd: /home/travis/build/arangodb/arangodb-php/tests/travis
./tests/travis/setup_arangodb.sh: line 68: /home/travis/build/arangodb/arangodb-php/tests/travis/ArangoDB-devel/bin/arangod_x86_64: No such file or directory
Check for arangod process
no 'arangod' process found
ARCH = x86_64
The command "./tests/travis/setup_arangodb.sh" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by jsteemann** [comment]
Yes, the TravisCI config is definitely out of date.
I'll check that tomorrow. I probably have to adjust the configuration much more than I thought in order to make it more up-to-date.

**Comment by jsteemann** [comment]
Update on this: the TravisCI configuration still needs some proper fixing.
It looks like the exact type of builds that the driver has used are not automatically published on arangodb.com/repositories. We'll probably change this to use some Docker-based setup, but it needs a few more days for the setup.

**Comment by jsteemann** [comment]
Merging this PR anyway now.

**Comment by sandrokeil** [comment]
@jsteemann For my tests, I use the bash script from the travisCI repository, see my [.travis.yml](https://github.com/sandrokeil/arangodb-php-driver-polyfill/blob/master/.travis.yml#L48-L50). But not all ArangoDB versions are available.

These lines are mandatory too.
```
after_script:
  - killall -s SIGTERM arangod_x86_64
```

**Comment by jsteemann** [comment]
Exactly this is the problem: the versions in the TravisCI repository seem to be outdated, and do not seem to be built automatically daily/nightly.
I think for the PHP driver and other drivers we will definitely move the TravisCI tests to use a Docker container with latest ArangoDB builds. I need someone here to set it up so these containers are built regularly, so it may take a day or two to set up.

**Comment by sandrokeil** [comment]
Alright, maybe [this example](https://github.com/sandrokeil/arangodb-php-driver/blob/master/.travis.yml) may help you.

**Comment by jsteemann** [comment]
Thanks. I now got a docker build and set up the tests to use it.

**Pull request merged**
