### PR TITLE
Issue #290 - Support PHP 8.1

### PR DESCRIPTION
**Pull request by Sweetchuck**
Issue #290 - Support PHP 8.1

### CODE REVIEW

**Comment by Geolim4** [comment]
Hello @Sweetchuck can you fix the PR please ? :D

**Comment by Sweetchuck** [comment]
@Geolim4 

1. Download a PDF
2. print it on papper
3. fill the form and sign it
4. send it back with fax (or other way)

No. I am not gonna do that.

ArangoDB should reconsider the contribution workflow.

I would happily contribute more. For example remove the `tests/.phpunit.result.cache` from the repository.

**Comment by Geolim4** [comment]
> @Geolim4
> 
>     1. Download a PDF
> 
>     2. print it on papper
> 
>     3. fill the form and sign it
> 
>     4. send it back with fax (or other way)
> 
> 
> No. I am not gonna do that.
> 
> ArangoDB should reconsider the contribution workflow.
> 
> I would happily contribute more. For example remove the `tests/.phpunit.result.cache` from the repository.

Wait what ? They require to sign and re-send a PDF ? oO
Didn't noticed that, my bad.
This new "CLA" trend is completely counterproductive.

**Comment by Sweetchuck** [comment]
I just rebased this branch to the latest „devel” branch.

**Comment by Sweetchuck** [comment]
The fail is totally irrelevant.

\ArangoDBClient\AdminTest::testGetServerMetrics
expected: arangodb_server_statistics_server_uptime_total
most closer actual: arangodb_server_statistics_server_uptime

----

But after that:
static::assertEquals("counter", $metric["type"]);
actual: gauge

---

static::assertTrue(is_numeric($metric["sum"])); \
Undefined index: sum \
/.../triagens/arangodb-php-3.x/tests/AdminTest.php:276

**Comment by Sweetchuck** [comment]
Related Issue: #294

**Pull request closed without merging**
