### PR TITLE
implementing JsonSerializable interface.

### PR DESCRIPTION
**Pull request by Ashafaat**
Signed-off-by: amirrezashafaat_desktop <amirrezashafaat@gmail.com>

Please note that for legal reasons we require you to sign the 
[Contributor Agreement](https://www.arangodb.com/documents/cla.pdf)
before we can accept your pull requests.

### CODE REVIEW

**Comment by jsteemann** [comment]
I am happy to accept the patch, but for legal reasons you will need to fill out and sign our [Contributor License Agreement](https://www.arangodb.com/documents/cla.pdf). You can scan and email the pdf file to cla@arangodb.com or send it via fax to +49-221-2722999-88. Sorry for the inconvenience, but once the agreement is there this PR and any following can be merged easily.

**Comment by Ashafaat** [comment]
I have send the CLA (exactly when i created the pull request)

**Comment by jsteemann** [comment]
@Ashafaat : alright, thanks! CLAs are processed manually, so I guess someone will put you on the list of contributors tomorrow :smile:, and I will then merge.

**Comment by Ashafaat** [comment]
hi,
CLA approved. (i recieved an email about that)

thanks.

**Comment by jsteemann** [comment]
Thanks for the PR!
I will address the failing test later today. It seems unrelated to your PR.

**Pull request merged**
